### ISSUE TITLE
Termux xterm error

### ISSUE THREAD

**Issue by Wjsfj51najdk** [vishalbiswas/vishalbiswas.github.io#1]
I compile termux xterm from your x11 branch but it is not working well
bash : cannot set terminal process group (-1) :Not a typewriter
bash : no job control in this shell

Also xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-60-ISO8859-1"

**Comment by vishalbiswas** [comment]
@xeffyr has setup an X11 repository for termux. It has xterm and many more gui packages. It is also semi-officially supported. Please, try xterm from their repo from -> https://github.com/termux/x11-packages

**Comment by xeffyr** [comment]
@Wjsfj51najdk See this about xterm https://github.com/termux/x11-packages/issues/5.
